# Generated by Django 5.2.4 on 2025-07-09 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField()),
                ('data_de_admissao', models.CharField()),
                ('data_de_vencimento_de_ferias', models.CharField()),
                ('saldo_de_ferias', models.CharField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoDeFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_de_descanso', models.CharField()),
                ('dias_vendidos', models.CharField()),
                ('email_gestor', models.CharField()),
                ('email_colaborador', models.CharField()),
                ('nome_colaborador', models.CharField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_de_ferias', to='core.card')),
            ],
            options={
                'verbose_name': 'Solicitacao De Ferias',
                'verbose_name_plural': 'Solicitacões De Ferias',
            },
        ),
    ]
