# Generated by Django 5.2.4 on 2025-07-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='email',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='nome',
            field=models.CharField(blank=True, null=True),
        ),
    ]
