# Generated by Django 5.2.4 on 2025-07-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card_email_card_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='data_de_vencimento_proxima',
            field=models.BooleanField(default=False),
        ),
    ]
