# Generated by Django 5.2.4 on 2025-07-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_card_data_de_vencimento_proxima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='data_de_admissao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='data_de_vencimento_de_ferias',
            field=models.DateTimeField(),
        ),
    ]
