# Generated by Django 5.2.4 on 2025-07-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_card_data_de_admissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodeferias',
            name='comunicacao_com_gestor',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solicitacaodeferias',
            name='ferias_finalizadas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacaodeferias',
            name='ferias_iniciadas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacaodeferias',
            name='ferias_rejeitadas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacaodeferias',
            name='fim_do_descanso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaodeferias',
            name='inicio_do_descanso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='solicitacaodeferias',
            name='observacao_do_gestor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaodeferias',
            name='solicitacao_aprovada',
            field=models.BooleanField(default=False),
        ),
    ]
