# Generated by Django 5.2.4 on 2025-07-10 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_solicitacaodeferias_comunicacao_com_gestor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaodeferias',
            name='email_colaborador',
        ),
        migrations.RemoveField(
            model_name='solicitacaodeferias',
            name='nome_colaborador',
        ),
        migrations.AddField(
            model_name='solicitacaodeferias',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
