# Generated by Django 5.2.4 on 2025-08-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_solicitacaodeferias_email_colaborador_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaodeferias',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Solicitacao De Ferias', 'verbose_name_plural': 'Solicitacões De Ferias'},
        ),
        migrations.AlterField(
            model_name='solicitacaodeferias',
            name='comunicacao_com_gestor',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
