# Generated by Django 5.2.4 on 2025-09-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_solicitacaodeferias_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaodeferias',
            name='motivo_rejeicao',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
