# Generated by Django 5.2.4 on 2025-09-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_solicitacaodeferias_motivo_rejeicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodeferias',
            name='comunicacao_com_gestor',
            field=models.FileField(upload_to='media/'),
        ),
    ]
